kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv00001
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pv00001"
